config/routes.rb
Ticketee::Application.routes.draw do
  
  
  devise_for :users # rutas para user registration, signup, editing and confirmation, and password retrieval

  root :to => "projects#index"   # Indicamos donde ir en la ruta raiz(pag inicial)
  
  resources :projects do
    resources :tickets
  end
  
  namespace :admin do
    root :to => "base#index"
    resources :users
  end
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  
    has_many :tickets, :dependent => :delete_all
  
    validates :name, :presence => true  # Validamos que se ha introducido campo name. 
                                        # Generalmente lo hace antes de meter en la base de datos. Si no
                                        # hay name no lo mete.
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  
  validates :title, :presence => true
  validates :description, :presence => true,
            :length => { :minimum => 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  def to_s
   "#{email} (#{admin? ? "Admin" : "User"})"
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
before_filter :authorize_admin!

  def index
    
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  
  before_filter :find_user, :only => [:show, :edit, :update, :destroy]
  
  def index
    @users = User.all(:order => "email")
  end
  
  def new
   @user = User.new
  end
  
  def show
  end
  
  def edit
  end

  def create
   @user = User.new(params[:user])
   set_admin
   if @user.save
     flash[:notice] = "User has been created."
     redirect_to admin_users_path
   else
     flash[:alert] = "User has not been created."
     render :action => "new"
   end
  end
  
  def update
   if params[:user][:password].blank?
     params[:user].delete(:password)
   end
   set_admin
   if @user.update_attributes(params[:user])
     flash[:notice] = "User has been updated."
     redirect_to admin_users_path
   else
     flash[:alert] = "User has not been updated."
     render :action => "edit"
   end
  end
  
  def destroy
    if @user == current_user
      flash[:alert] = "You cannot delete yourself!"
    else
      @user.destroy
      flash[:notice] = "User has been deleted."
    end
    redirect_to admin_users_path
  end
  
  private
  def find_user
    @user = User.find(params[:id])
  end
  
  def set_admin
    @user.admin = params[:user][:admin] == "1"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  # Cualquier metodo definido aqui esta disponible para todos los controladores
  
  private
  
  def authorize_admin!
    authenticate_user!    # Para asgurarse de que esta sign in, si no lo esta, te lo pide
    unless current_user.admin?
      flash[:alert] = "You must be an admin to do that."
      redirect_to root_path
    end
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  # Miramos si es admin o no para dejar hacer accion
  before_filter :authorize_admin!, :except => [:index, :show]
  # Indicamos que antes de show, edit, update y destroy se haga find_project
  before_filter :find_project, :only => [:show,
                                         :edit,
                                         :update,
                                         :destroy]
  
  def index
    @projects = Project.all   # Sacamos todos de la base de datos
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(params[:project])
    if @project.save   # Si se ha metido campo name deja meter en la base de datos
      flash[:notice] = "Project has been created."
      redirect_to @project
    else  # Si no se ha metido campo name
      flash[:alert] = "Project has not been created."
      render :action => "new"
    end
  end
  
  def show
    @project = Project.find(params[:id])
  end
  
  def edit
    @project = Project.find(params[:id])
  end
  
  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated."
      render :action => "edit"
    end
  end
  
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "Project has been deleted."
    redirect_to projects_path   # Volvemos a la pagina con todos los proyectos
  end
  
  # Fijarse: los que no tienen vista es porque redirigen de alguna manera al terminar la accion
  
  private
    def find_project
      @project = Project.find(params[:id])
      rescue ActiveRecord::RecordNotFound   # Capturamos la excepcion cuando accedemos a proyecto que no existe
      flash[:alert] = "The project you were looking" +
         " for could not be found."   # Mostramos el mensaje
      redirect_to projects_path       # Y vamos a la web principal
    end
  
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :find_project  # Lo hace de cualquier accion
  before_filter :find_ticket, :only => [:show,
                                        :edit,
                                        :update,
                                        :destroy]
  
  def new
    @ticket = @project.tickets.build # build asocia el nuevo objeto ticket con el objeto project
  end                                # foreign key es project_id
  
  
  def create
    @ticket = @project.tickets.build(params[:ticket].merge!(:user => current_user))
    if @ticket.save
      flash[:notice] = "Ticket has been created."
      redirect_to [@project, @ticket]  # Te lleva al ticket adecuado dentro del project correspondiente
    else
      flash[:alert] = "Ticket has not been created."
      render :action => "new"
    end
  end
  
  # las funciones del private ya hacen todo lo que hay que hacer
  def show
  end
  
  def edit
  end
  
  def update
    if @ticket.update_attributes(params[:ticket])
      flash[:notice] = "Ticket has been updated."
      redirect_to [@project, @ticket]
    else
      flash[:alert] = "Ticket has not been updated."
      render :action => "edit"
    end
  end
  
  def destroy
    @ticket.destroy
    flash[:notice] = "Ticket has been deleted."
    redirect_to @project
  end
  
  
  # Se usa project_id en lugar de id solo para diferenciar de cuando buscamos el id de un ticket que sera solo id
  private
    def find_project
      @project = Project.find(params[:project_id])
    end
    
    def find_ticket
      @ticket = @project.tickets.find(params[:id])
    end
   
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Ticketee").join(" - ") unless parts.empty?
     end
    end
  end
  
  def admins_only(&block)   # El block es el codigo entre el begin y el end en la vista
   block.call if current_user.try(:admin?)  # Ejecuta el bloque solo si current_user.try(:admin?) es true
   nil
  end
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/base/index.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= link_to "Users", admin_users_path %>
Welcome to Ticketee's Admin Lounge. Please enjoy your stay.

app/views/admin/users/_form.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= form_for [:admin, @user] do |f| %>
<%= f.error_messages %>
<p>
  <%= f.label :email %>
  <%= f.text_field :email %>
</p>
<p>
  <%= f.label :password %>
  <%= f.password_field :password %>
</p>
<p>
  <%= f.check_box :admin %>
  <%= f.label :admin, "Is an admin?" %>
</p>
<%= f.submit %>
<% end %>

app/views/admin/users/edit.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= render "form" %>

app/views/admin/users/index.html.erb
<h1>Admin::Users#index</h1>

<%= link_to "New User", new_admin_user_path %>
<ul>
<% @users.each do |user| %>
  <li><%= link_to user, [:admin, user] %></li>
<% end %>
</ul>

app/views/admin/users/new.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<h2>New User</h2>
<%= render "form" %>

app/views/admin/users/show.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<h2><%= @user %></h2>
<%= link_to "Edit User", edit_admin_user_path(@user) %>

<%= link_to "Delete User", admin_user_path(@user), :method => :delete,
:confirm => "Are you sure you want to delete this user?" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
     <% if content_for?(:title) %>
       <%= yield(:title) %>
     <% else %>
       Ticketee
     <% end %>
  </title>
  <%= stylesheet_link_tag    "application" %>  # hojas de estilos de app/assets/stylesheets
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>  
 <%= admins_only do %>
 <%= link_to "Admin", admin_root_path %><br>
 <% end %>
</nav>
 
<h1><%= link_to "Ticketee", root_path %></h1>

<% if user_signed_in? %>
  Signed in as <%= current_user.email %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %>
  <%= link_to "Sign in", new_user_session_path %>
<% end %>
  
<%= yield %>  # En cada momento carga la vista de la accion correspondiente
  
<% flash.each do |key, value| %>    # Esto carga los mensajes flash
  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>

</body>
</html>

app/views/projects/_form.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "_form.html" %>

<!-- asocia @project al de la action new o edit -->
<%= form_for(@project) do |f| %>  
  <%= f.error_messages %>
  <p>
   <%= f.label :name %>
   <%= f.text_field :name %>
  </p>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "edit.html" %>

<h2>Edit project</h2>
<%= render "form" %>

app/views/projects/index.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= admins_only do %>   <!-- Solo los admin puedes crear un nuevo proyecto -->
<%= link_to "New Project", new_project_path %>
<% end %>

<h2>Projects</h2>
<ul>
  <% @projects.each do |project| %>
    <li><%= link_to project.name, project %></li>
  <% end %>
</ul>

<%= "index.html" %>

app/views/projects/new.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "new.html" %>

<h2>New project</h2>
<%= render "form" %>

app/views/projects/show.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "show.html" %>

<!-- Hacemos uso de la funcion title en el helper para hacer que el titulo sea dinamico
dependiendo de la accion que se esta llevando a cabo -->
<% title(@project.name, "Projects") %>  

<h2><%= @project.name %></h2>

<%= admins_only do %>
<%= link_to "Edit Project", edit_project_path(@project) %>
<%= link_to "Delete Project", project_path(@project), :method => :delete,
:confirm => "Are you sure you want to delete this project?" %>
<% end %>

<!-- Nested routing en lugar de simple routing (new_ticket_path), ya que queremos
crear un ticket para un cierto proyecto. Tiene que tomar como argumento el proyecto
correspondiente -->
<%= link_to "New Ticket", new_project_ticket_path(@project) %> 

<ul id='tickets'>
  <% @project.tickets.each do |ticket| %>
    <li>
      #<%= ticket.id %> - <%= link_to ticket.title, [@project, ticket] %>
    </li>
  <% end %>
</ul>

app/views/tickets/_form.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "_form.html" %>

<%= form_for [@project, @ticket] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>
  <%= f.submit %>
<% end %>

app/views/tickets/edit.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "edit.html" %>

<h2>Editing a ticket in <%= @project.name %></h2>
<%= render "form" %>

app/views/tickets/new.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "new.html" %>

<h2>New Ticket</h2>
<%= render "form" %>

app/views/tickets/show.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "show.html" %>

<!-- Simple_format transforma los finales de linea del form en <br> -->
<div id='ticket'>
  <h2><%= @ticket.title %></h2>
  <!-- edit_project_ticket_path 
  edit_project_ticket_path(@project, @ticket)-->
  <%= link_to "Edit Ticket", [:edit, @project, @ticket] %> 
  <%= link_to "Delete Ticket", [@project, @ticket], :method => :delete,
             :confirm => "Are you sure you want to delete this ticket?" %>
  <%= simple_format(@ticket.description) %>
  
  <br><small>Created by <%= @ticket.user.email %></small>
</div>